[package]
name = "gauge_cap"
edition = "2024"

[addresses]
gauge_cap = "0x0"

[dev-dependencies]

[dev-addresses]

[dependencies.Sui]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework/packages/sui-framework"
rev = "framework/mainnet"
override = true
