[package]
name = "move_stl"
edition = "2024"

[addresses]
move_stl = "0x0"

[dependencies.Sui]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework/packages/sui-framework"
rev = "framework/mainnet"
override = true
